[versions]
commonmark = "0.25.1"

[libraries]
kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10"
commonmark-core = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmark-ext-footnotes = { module = "org.commonmark:commonmark-ext-footnotes", version.ref = "commonmark" }
commonmark-ext-headingAnchor = { module = "org.commonmark:commonmark-ext-heading-anchor", version.ref = "commonmark" }
commonmark-ext-strikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
liqp = "nl.big-o:liqp:0.9.2.3"
clikt = "com.github.ajalt.clikt:clikt:5.0.0"
snakeyaml = "org.yaml:snakeyaml:2.4"
commonsText = "org.apache.commons:commons-text:1.14.0"
junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
