name: build

on: [push, pull_request]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: bundle exec jekyll build
