name: site

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.message }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: docker build -t jw .
      - run: docker run --volume="$PWD/site:/blog" jw /blog

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: site
          path: site/out
          if-no-files-found: error

      - id: message
        run: git log "--format=message=%h %s" -n 1 $GITHUB_SHA >> "$GITHUB_OUTPUT"

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version
      - run: ./gradlew check

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'JakeWharton/jakewharton.com' }}
    needs:
      - compile
      - check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: package*json
          sparse-checkout-cone-mode: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      - run: npm ci

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: site
          path: out

      - name: Preview deploy
        if: ${{ github.ref != 'refs/heads/trunk' }}
        run: node_modules/.bin/netlify deploy --no-build --site jakewharton-com --dir out --message "${{ needs.build.outputs.message }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Production deploy
        if: ${{ github.ref == 'refs/heads/trunk' }}
        run: node_modules/.bin/netlify deploy --no-build --site jakewharton-com --dir out --message "${{ needs.build.outputs.message }}" --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
